### ISSUE TITLE
常见问题FQA

### ISSUE THREAD

**Issue by PlainWizard** [wxext/web#1]
# 这里用于提交整理常见问题

## Q: 有没有文档
按照README.md流程安装使用 https://github.com/wxext/wxext
无法使用请查看安装文档 https://www.wxext.cn/app/install.html
一个页面查看和管理微信 https://www.wxext.cn/app/demo.html
api全部功能可在这里测试 https://www.wxext.cn/app/test.html
## Q: 插件拦截了所有请求消息
启用了插件可以拦截除了停止插件以为的所有请求,在测试页面停止插件
## Q: 如何写扩展
在线开发页面 https://www.wxext.cn/app/run.html
采用语法 JScript语法，支持大部分JavaScript方法，同时支持c#方法
## Q: 如何收消息
+ 插件 onmsg 会有所有消息通知
+ websocket地址：ws://127.0.0.1:8202/wx 可接收所有消息
+ 功能测试页面的 添加通知 notify 可将消息通知到http服务器
## Q: 找不到微信路径
启动参数里添加path参数指定微信路径
## Q: 请求报错JsonReader
参数json的格式错误

**Comment by q472448760** [comment]
{
    "msg": "运行超时,请稍后重试.4294967295",
    "pid": 0,
    "data": true,
    "method": "run_Recv"
}

请稍后重试,如重试多次都是一样，请运行安装目录下的 TestRun.exe 进行运行环境测试

**Comment by q472448760** [comment]
插件 onmsg 会有所有消息通知
websocket地址：ws://127.0.0.1:8202/wx 可接收所有消息
功能测试页面的 添加通知 notify 可将消息通知到http服务器

上面三中接收消息只有文本消息吗？

可以增加微信系统的消息和自己发出的消息推送吗？

A:可以收到自己其他平台推送的消息，不支持本机发出的消息。重新授权下，添加了其他类型的消息

**Comment by PlainWizard** [comment]
## Q: 如何外网访问
软件服务默认只允许本地内网访问，如需外网访问可在安装目录下新建 allowNet 文件，无后缀。
重启生效，启动服务时会提示是否可以外网访问
启用外网访问后，可使用插件过滤外网请求，插件相关功能仅允许内网访问，防止外网关闭插件

**Comment by q472448760** [comment]
授权失败,token不匹配,not match mac

**Comment by q472448760** [comment]
获取登录信息提示下面错误，获取登录的消息没有返回登录消息
{
    "msg": "timeOut"
}
